<?php

declare(strict_types=1);

/**
 * Implements hook_theme_suggestions_HOOK_alter for blocks.
 *
 * See https://www.drupal.org/docs/develop/theming-drupal/creating-sub-themes.
 */
function brookeolivero_theme_suggestions_block_alter(&$suggestions, $variables) {
  // Loads theme suggestions for blocks from parent theme.
  foreach ($suggestions as &$suggestion) {
    $suggestion = str_replace('olivero_', 'brookeolivero_', $suggestion);
  }
}
